- name: Restart machine
  raw: shutdown /r /f /c "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: Waiting for server to come back
  local_action: wait_for
                host={{ inventory_hostname }}
                state=started
                timeout=180
