---
- name: Deploy connect
  command: dcos package install confluent-connect --package-version={{ connect_ver }} --options "{{ item }}" --yes
  with_items:
    - "../../dcos/dap-uk/options\ json\ -\ install\ and\ upgrade/connect/connect-config.json"

- name: Check if service has been deployed correctly
  command: bash -c "dcos marathon app list | grep "/connect" | awk '{print $6}'"
  register: testit
  retries: 30
  until: testit.stdout == "---"