---
# file: roles/common/tasks/register_spacewalk_rhel.yml

- name: Check if Spacewalk client is already installed
  command: rpm -q "{{item}}"
  register: packages
  ignore_errors: yes
  with_items: "{{spacewalk_packages}}"

- name: Check if at least one package is missing
  set_fact: 
    package_missing: true
  when: item.rc != 0
  with_items: "{{packages.results}}"

- debug: var=package_missing

- name: If Spacewalk client is not installed, disable rhnplugin and use only the correct repository
  ini_file: dest=/etc/yum/pluginconf.d/rhnplugin.conf 
            section=main
            option=enabled
            value=0
  when: package_missing == true
  ignore_errors: True

- name: Disable all repositories CentOS
  command: yum-config-manager --disable "CentOS-7 - Extras" "CentOS-7 - Updates" "CentOS-7 - Base"

- name: If Spacewalk client is not installed, copy spacewalk-repo to /etc/yum.repos.d/
  copy: src=spacewalk_rhel{{ ansible_distribution_major_version }}.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644
  when: package_missing == true

- name: Install Spacewalk client
  package: name="{{item}}" state=latest
  with_items: "{{spacewalk_packages}}"

- name: Remove the repository spacewalk-repo
  file: path=/etc/yum.repos.d/spacewalk_rhel{{ ansible_distribution_major_version }}.repo state=absent

- name: If systemid doesn't exist, register to spacewalk
  command: rhnreg_ks --serverUrl=http://sasv02fj.saipemnet.saipem.intranet/XMLRPC --activationkey=1-saipem creates=/etc/sysconfig/rhn/systemid

- name: Disable gpgcheck
  ini_file: dest=/etc/yum/pluginconf.d/rhnplugin.conf 
            section=main
            option=gpgcheck
            value=0

- name: Enable rhnplugin for use spacewalk repos
  ini_file: dest=/etc/yum/pluginconf.d/rhnplugin.conf 
            section=main
            option=enabled
            value=1
