---
- name: Deploy confluent-kafka
  command: dcos package install confluent-kafka --package-version={{ kafka_ver }} --options "{{ item }}" --yes
  with_items:
    - "../../dcos/dap-uk/options\ json\ -\ install\ and\ upgrade/confluent-kafka/confluent-kafka.json"

- name: Check if service has been deployed correctly
  command: bash -c "dcos marathon app list | grep "confluent-kafka" | awk '{print $6}'"
  register: testit
  retries: 30
  until: testit.stdout == "---"