---
- name: Deploy cassandra
  command: dcos package install beta-cassandra --package-version={{ cassandra_ver }} --options "{{ item }}" --yes
  with_items:
    - "../../dcos/dap-uk/options\ json\ -\ install\ and\ upgrade/cassandra/beta-cassandra.json"

- name: Check if service has been deployed correctly
  command: bash -c "dcos marathon app list | grep "cassandra" | awk '{print $6}'"
  register: testit
  retries: 30
  until: testit.stdout == "---"