---
- name: reboot sequence
  changed_when: "true"
  debug: msg='trigger machine reboot sequence'
  notify:
   - get current time
   - reboot system
   - waiting for all machines to come back online
   - verify a reboot was actually initiated
- name: get current time
  command: /bin/date +%s
  register: before_reboot
  sudo: false
- name: reboot system
  shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
- name: waiting for all machines to come back online
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=220
  sudo: false
- name: verify a reboot was actually initiated
  shell: (( `date +%s` - `awk -F . '{print $1}' /proc/uptime` > {{ before_reboot.stdout }} ))
  sudo: false
