---
- name: Deploy replicator
  command: dcos package install confluent-replicator --package-version={{ replicator_ver }} --options "{{ item }}" --yes
  with_items:
    - "../../dcos/dap-uk/options\ json\ -\ install\ and\ upgrade/replicator/replicator.json"  

- name: Check if service has been deployed correctly
  command: bash -c "dcos marathon app list | grep "replicator" | awk '{print $6}'"
  register: testit
  retries: 30
  until: testit.stdout == "---"