---
- name: Deploy etcd-browser
  command: dcos marathon app add "{{ item }}"
  with_items:
    - "../../dcos/dap-uk/marathon\ json\ -\ running/etcd-browser/marathon.json"

- name: Check if service has been deployed correctly
  command: bash -c "dcos marathon app list | grep "etcd-browser" | awk '{print $6}'"
  register: testit
  retries: 30
  until: testit.stdout == "---"