#!/usr/bin/perl
# nagios: -epn
# Author : jakubowski Benjamin
# Date : 19/12/2005
# check_win_snmp_cpuload.pl IP COMMUNITY PORT warning critical

sub print_usage {
    print "check_win_snmp_cpuload.pl IP COMMUNITY warning critical\n";
}

$PROGNAME = "check_win_snmp_cpuload.pl";

if  ( @ARGV[0] eq "" || @ARGV[1] eq "" || @ARGV[2] eq "" ) {
    print_usage();
    exit 0;
}

$STATE_CRITICAL = 2;
$STATE_WARNING = 1;
$STATE_UNKNONW = 3;

$STATE_OK = 0;

$IP=@ARGV[0];
$COMMUNITY=@ARGV[1];
$warning=@ARGV[2];
$critical=@ARGV[3];
$resultat =`snmpwalk -v 1 -c $COMMUNITY $IP 1.3.6.1.2.1.25.3.3.1.2`;

$perf = "";

if ( $resultat ) {
    @pourcentage = split (/\n/,$resultat);
    $j=0;
    foreach ( @pourcentage ) {
	s/HOST-RESOURCES-MIB::hrProcessorLoad.\d+ = INTEGER://g;	
	$use_total+=$_;
        $j++;
    }
    #$use = $use_total / $j;
    $use = sprintf "%.2f", $use_total/$j;

    if ( $use < $warning ) {
	print "OK : Overall CPU load $use% - ";
#	exit $STATE_OK;
    } elsif ( $use => $warning && $use < $critical ) {
        print "WARNING : Overall CPU load $use% - ";
#        exit $STATE_WARNING;
    } else {
        print "CRITICAL : Overall CPU load :$use% - ";
#        exit $STATE_CRITICAL;
    }

# Getting Individual CPU Load
    $i=0;
    foreach ( @pourcentage ) {
	s/HOST-RESOURCES-MIB::hrProcessorLoad.\d+ = INTEGER://g;	
	s/ //g;
	$cpuuse=$_;
	print "CPU_$i:$cpuuse% ";
	$i++;
	$perf .= "CPU_$i=$_% ";
    }
    print "| $perf\n";
    exit $STATE_OK;
} else {
    print "Unknown  : No response\n";
    exit $STATE_UNKNONW;
}

