---
- name: Deploy spark
  command: dcos package install spark --package-version={{ schema_ver }} --options "{{ item }}" --yes
  with_items:
    - "../../dcos/dap-uk/options\ json\ -\ install\ and\ upgrade/spark/spark.json"  

- name: Check if service has been deployed correctly
  command: bash -c "dcos marathon app list | grep "spark" | awk '{print $6}'"
  register: testit
  retries: 30
  until: testit.stdout == "---"